name: timetable_processor
description: A university timetable file processor
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  excel: ^4.0.6
  csv: ^6.0.0
  file_picker: ^8.1.7
  logger: ^2.5.0
  path: ^1.9.1
  ffi: ^2.1.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
